services:
  - type: web
    name: dashboard-ondas-calor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --host 0.0.0.0 --port $PORT --workers 1 --timeout 120
    envVars:
      - key: PORT
        value: 8050
      - key: PYTHON_VERSION
        value: 3.9.18

